# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginM2LTestinSelenium():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginM2LTestinSelenium(self):
    self.driver.get("https://med2lab.com/")
    self.driver.set_window_size(1696, 1026)
    self.driver.find_element(By.CSS_SELECTOR, ".btn-light").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("K4_kiat.neo@med2lab.com")
    self.driver.find_element(By.NAME, "password").send_keys("K4_kiat.neo@2021")
    self.driver.find_element(By.ID, "button_submit_form").click()
  
